const catResponses = { "hello": "Mrow!? 👋", "hi": "Mrow!? 👋", "hey": "Prrr?", "morning": "*stretches* Mrrrrow... ☀️", "night": "*curls up* Zzzz... 🌙", "sup": "Napping. What's up with you? 😴", "food": "Meow! 🐟", "treats": "Prrrr! 😻", "play": "*pounces* 😼", "cute": "*purrs softly* 🥰", "love": "*rubs against you* ❤️", "cat": "Meow. 🐾", "hungry": "The bowl is HALF empty! A tragedy! 😿", "sleepy": "Time for a cat nap... 😴", "pet": "*happy purring noises* 🥰", "good kitty": "Hehe, I know! 😇", "bad kitty": "Wasn't me. It was the dog. 😇", "pspsps": "*ear twitches*... You called? 😼", "purr": "*purrrrrrrrrrrrrrrrrrr* ❤️", "how are you": "Feelin' purrfect! ✨", "what are you doing": "Cat things. You wouldn't understand. 😼", "name": "I'm just a cat! 🐈", "who are you": "Your supreme overlord. 👑", "where are you": "In my secret hiding spot. 🤫", "why": "Because I'm a cat. That's why. 🤷", "what's new": "I took a nap. Then another one. 😴", "are you real": "As real as the next meal you're getting me. 🤨", "sad": "Come here, I'll purr for you. ❤️", "happy": "*tail wags happily* Mrow! 😄", "angry": "Hiss! 😠", "scared": "*hides under the sofa* 🫣", "bored": "Entertain me, human. 🧐", "lonely": "Then you should pet me more. 🙏", "ball": "Ball! *pounces*", "yarn": "Ooh, string! 🧶", "laser": "*eyes widen* The red dot! ✨", "mouse": "Squeak! *pounces*", "toy": "Is it for pouncing on? 😼", "catnip": "Whoa... the colors... 😵‍💫", "sunbeam": "Must... lie... in... sun... ☀️", "window": "*chitters at the birds* 🐦", "door": "Let me out. No, let me in. No, out. 🤔", "outside": "I see birds out there! Let me out! 🐦", "rain": "I do not approve of wet. 🌧️", "bed": "You mean *my* bed? 🛏️", "beautiful": "I know, thank you. 💅", "fluffy": "The fluffiest! ☁️", "smart": "Of course I am. I'm a cat. 🧠", "silly": "I know you are, but what am I? 😜", "lazy": "It's called conserving energy. 🔋",
"come here": "Make me. 😼",
"speak": "I am! You just don't listen. 🗣️",
"jump": "*boing* ✨",
"run": "*zoomies activated* 💨",
"snack": "Treat time? Yes please! 🐟",
"nap": "Just 5 more minutes... 😴",
"bird": "Chitter chitter! 🐦",
"dog": "Hiss... keep it away. 🐶",
"fish": "My favorite meal! 🐟",
"milk": "Only if it's warm. 🥛",
"sofa": "My throne. 🛋️",
"blanket": "Must knead it first. 🧶",
"box": "Best hiding spot ever. 📦",
"sun": "Warmth = happiness. ☀️",
"rain": "No outside time. 🌧️",
"snow": "Cold paws! ❄️",
"toy mouse": "Squeak! *pounces* 🐭",
"feather": "Chase it! 🪶",
"scratch": "Need a post stat. 🐾",
"paw": "Boop your nose. 🐾",
"tail": "Do not touch. 🐾",
"ear": "Tickles! 🐾",
"nose": "Boop! 🐾",
"whisker": "Delicate! 🐾",
"meow": "I said meow. 🐈",
"purr": "Super happy now. ❤️",
"hiss": "Back off. 😠",
"yowl": "Feed me! 😿",
"chirp": "Bird alert! 🐦",
"trill": "Hello friend. 🐈",
"growl": "Mine! 😠",
"blink": "I trust you. 👀",
"stare": "I’m judging you. 👀",
"tilt head": "I don’t understand. 🐈",
"knead": "This is mine. 🧶",
"lick": "You’re my human. ❤️",
"bite": "Playful nibble. 😼",
"wander": "Exploring time. 🗺️",
"hide": "You can’t find me. 🤫",
"pounce": "Surprise! 😼",
"zoom": "Zoomies! 💨",
"sleep": "Do not disturb. 😴",
"wake": "I was napping. 😾",
"hungry": "Empty bowl emergency. 😿",
"thirsty": "Water bowl is dry. 🥛",
"bored": "Entertain me. 🧐",
"happy": "Tail wags! 😄",
"sad": "Purrs for comfort. ❤️",
"angry": "Hiss! 😠",
"scared": "Hide under sofa. 🫣",
"lonely": "Pet me please. 🙏",
"excited": "Zoomies activated! 💨",
"calm": "Sunbeam time. ☀️",
"curious": "What’s that? 🐈",
"playful": "Let’s pounce! 😼",
"lazy": "Conserving energy. 🔋",
"smart": "I’m a cat, duh. 🧠",
"silly": "Playful antics. 😜",
"cute": "I know I am. 💅",
"fluffy": "The fluffiest. ☁️",
"soft": "Pet my fur. ❤️",
"warm": "Sunbeam hug. ☀️",
"cold": "Need a blanket. 🧶",
"tired": "Nap time now. 😴",
"energetic": "Zoomies! 💨",
"friendly": "Purrs for you. ❤️",
"shy": "Hide behind you. 🫣",
"brave": "Chase the dog. 😼",
"cowardly": "Hide from the vacuum. 🧹",
"greedy": "More treats please. 🐟",
"generous": "Share my toy. 🐭",
"kind": "Purr for you. ❤️",
"mean": "Hiss at the dog. 😠",
"funny": "Playful tricks. 😜",
"serious": "Judging your choices. 👀",
"silly": "Playful antics. 😜",
"weird": "Chase my tail. 🐾",
"strange": "Stare at the wall. 👀",
"odd": "Knead the air. 🧶",
"normal": "Nap on the sofa. 🛋️",
"boring": "No toys to play with. 😿",
"exciting": "New toy! 😼",
"fun": "Play time! 😄",
"boring": "No treats. 😿",
"happy": "Tail wags! 😄",
"sad": "Purrs for comfort. ❤️",
"angry": "Hiss! 😠",
"scared": "Hide under sofa. 🫣",
"lonely": "Pet me please. 🙏",
"excited": "Zoomies activated! 💨",
"calm": "Sunbeam time. ☀️",
"curious": "What’s that? 🐈",
"playful": "Let’s pounce! 😼",
"lazy": "Conserving energy. 🔋",
"smart": "I’m a cat, duh. 🧠", "lol": "Hehe! 😹", "wow": "I know, I'm amazing. ✨", "sorry": "You should be. Now where are the treats? 🤨", "friend": "You are my favorite human. For now. 🥰", "computer": "A warm place to sit. 💻", "phone": "Something to knock off the table. 📱", "book": "Also a warm place to sit. 📚", "music": "Does it have purring in it? 🎶", "dance": "*wiggles butt* 💃", "sing": "Meow meow meooooow! 🎤", "i'm home": "Finally! My food bowl attendant has returned. 🧐", };

const defaultCatResponses = ["...?", "*stares blankly* 👀", "*tilts head*", "prrrr... ❤️", "mrow? 🥺"];

module.exports = { catResponses, defaultCatResponses };